//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rio_Doc
    {
        public int SN { get; set; }
        public string DocName { get; set; }
        public string DocContent { get; set; }
        public string DocPath { get; set; }
        public Nullable<int> HitCount { get; set; }
        public string Extension { get; set; }
        public string CreateID { get; set; }
        public string CreateName { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string ModifyId { get; set; }
        public string ModifyName { get; set; }
        public Nullable<System.DateTime> ModifyDate { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
