//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RioManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vw_Account
    {
        public string PicName { get; set; }
        public string PicPath { get; set; }
        public int SN { get; set; }
        public string ID { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public string AccountContent { get; set; }
        public string Email { get; set; }
        public int PicSN { get; set; }
        public bool IsEnable { get; set; }
        public bool IsDelete { get; set; }
        public string CreateID { get; set; }
        public string CreateName { get; set; }
        public System.DateTime CreateDate { get; set; }
        public string ModifyID { get; set; }
        public string ModifyName { get; set; }
        public System.DateTime ModifyDate { get; set; }
        public string CoverName { get; set; }
        public string CoverPicPath { get; set; }
        public Nullable<int> AccountSN { get; set; }
        public Nullable<int> CoverSN { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
    }
}
